[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15132212846616546060
xla_global_id: -1
]
Before datagen..
Found 2800 images belonging to 2 classes.
Datagen completed..
Found 800 images belonging to 2 classes.
Data Generation Completed
Training Starting..
Epoch 1/30
/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/rmsprop.py:135: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)
[34m[1mwandb[39m[22m: [33mWARNING[39m The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
WARNING:tensorflow:From /home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/ops/nn_ops.py:5219: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`















132/500 [======>.......................] - ETA: 1:25 - loss: 0.9710 - acc: 0.4697
Traceback (most recent call last):
  File "/home/akshat/Documents/Github/Homoglyph_Phishing_Detection/code/train.py", line 98, in <module>
    obj.SimpleCNN()
  File "/home/akshat/Documents/Github/Homoglyph_Phishing_Detection/code/train.py", line 63, in SimpleCNN
    model.fit(self.train_it,validation_data=self.validation_it, steps_per_epoch=500, epochs=30, verbose=1, callbacks=[WandbCallback()])
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/wandb/integration/keras/keras.py", line 173, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/keras/engine/training.py", line 1409, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 915, in __call__
    result = self._call(*args, **kwds)
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py", line 947, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 2453, in __call__
    return graph_function._call_flat(
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 1860, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 497, in call
    outputs = execute.execute(
  File "/home/akshat/Documents/Github/homo_env/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
KeyboardInterrupt